# Generated by Django 3.2.3 on 2021-06-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alg', '0002_rename_allegry_allergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
